### ISSUE TITLE
关于新建java类型文件的一个小建议

### ISSUE THREAD

**Issue by oicq1699** [rectcircle/new-file-by-type#1]
我找了很久，才找到这个扩展，非常好用。帮我省了不少工作量。
在开发java项目时，我一般是基于maven的项目结构，用该插件生成新文件时，默认包名前面多了个main.java(或者是src目录其实是 src/main/java，但是默认是src），能不能提供一个配置项，可以设定默认src的起始目录（相对路径）？

**Comment by rectcircle** [comment]
感谢使用，没想到真的有用户使用这个扩展。关于这个扩展，现在可能还有一些问题，且代码比较混乱。近期我刚好有时间，需要进行重构。这个问题我记下了。有什么功能需求欢迎继续评论。

**Comment by rectcircle** [comment]
#2
